%% betaSweepSolver.m
%  Beta sweep: flutter margin vs. beta angle for the ar1 laminate at 6 mm.
%
%  PIPELINE
%  --------
%  Step 0  Load lam_sweep.json  (generated by Python --sweep flag)
%  Step 1  Print structural table  → cross-check vs. Python output
%  Step 2  Load flight data        → find critical (max-q) flight point
%  Step 3  Build mesh + BCs        → same geometry for every beta
%  Step 4  Build mass matrix ONCE  → does not change with beta
%  Step 5  Beta loop:
%            a. Build D_flex from JSON values
%            b. Build stiffness matrix K
%            c. Modal analysis  → natural frequencies + mode shapes
%            d. Compute GAF at the critical flight point
%            e. Run flutter / divergence solver
%            f. Print one row of the results table
%  Step 6  Plot results and save
%
%  VERIFICATION CHECKPOINTS
%  ------------------------
%  (A) Structural table  — must match Python --sweep output exactly
%  (B) Natural frequencies — should vary smoothly and monotonically with beta
%  (C) Flutter margin — expected to peak near beta = 5–10 deg (highest k_weiss)
%
%  Run from the supersonic_fin_flutter_matlab/ directory.

clear; clc; close all;

BASE = fileparts(mfilename('fullpath'));
fprintf('=== Beta Sweep Flutter Solver ===\n');
fprintf('    Working directory: %s\n\n', BASE);

%% -----------------------------------------------------------------------
%% Step 0.  Load lam_sweep.json
%% -----------------------------------------------------------------------
sweepFile = fullfile(BASE, 'configs', 'lam_sweep.json');
if ~isfile(sweepFile)
    error(['lam_sweep.json not found.\n' ...
           'Generate it first:\n' ...
           '  cd python_core\n' ...
           '  python inplaneG_v5.py --sweep --sweep-json ../configs/lam_sweep.json']);
end

raw     = jsondecode(fileread(sweepFile));
info    = raw.sweep_info;
configs = raw.configs;           % [nConfigs x 1] struct array

t       = info.t_mm * 1e-3;     % mold thickness [m]
rho_m   = info.rho_mat_kgm3;    % material density [kg/m3]
nu_eff  = 0.3;                   % effective in-plane Poisson ratio
nCfg    = numel(configs);

fprintf('Loaded %d beta configurations  (%.0f to %.0f deg)\n', ...
        nCfg, configs(1).beta_deg, configs(end).beta_deg);
fprintf('  t = %.1f mm    rho = %.0f kg/m3\n\n', t*1e3, rho_m);

%% -----------------------------------------------------------------------
%% Step 1.  Structural verification table
%%          → Values must match the Python --sweep printout exactly.
%%            If they differ, the JSON was not regenerated after a code change.
%% -----------------------------------------------------------------------
fprintf('STEP 1 — STRUCTURAL VERIFICATION (must match Python output)\n');
fprintf('  %-5s  %-9s  %-9s  %-9s  %-9s  %-9s  %-9s\n', ...
        'beta', 'D11[N.m]', 'D22[N.m]', 'D66[N.m]', 'D16[N.m]', 'D26[N.m]', 'k_weiss');
fprintf('  %s\n', repmat('-', 1, 66));
for ic = 1:nCfg
    c = configs(ic);
    fprintf('  %-5.0f  %-9.3f  %-9.3f  %-9.3f  %-9.4f  %-9.4f  %-9.5f\n', ...
            c.beta_deg, c.D11_Nm, c.D22_Nm, c.D66_Nm, c.D16_Nm, c.D26_Nm, c.k_weiss);
end
fprintf('\n');

%% -----------------------------------------------------------------------
%% Step 2.  Load flight data → critical flight point (max dynamic pressure)
%% -----------------------------------------------------------------------
fprintf('STEP 2 — Loading flight data...\n');
csvFile = fullfile(BASE, 'data', 'flight_data.csv');
if ~isfile(csvFile)
    error('flight_data.csv not found at %s', csvFile);
end
opts = detectImportOptions(csvFile, 'CommentStyle', '#');
opts.VariableNames = {'time_s', 'altitude_ft', 'Vz_ms'};
tbl  = readtable(csvFile, opts);

h_m  = tbl.altitude_ft * 0.3048;
V    = abs(tbl.Vz_ms);
flightPts = struct([]);
for i = 1:height(tbl)
    [rho_i, a_i, ~, ~] = aero.isaAtmosphere(h_m(i));
    M_i = V(i) / a_i;
    % M >= 1.05 ensures beta = sqrt(M^2-1) >= 0.312; piston theory validity per Lighthill (1953) and NACA TN 4021
    if M_i >= 1.05
        fp.Mach=M_i; fp.a=a_i; fp.rho=rho_i;
        fp.U=V(i); fp.q_inf=0.5*rho_i*V(i)^2;
        fp.h_m=h_m(i); fp.time=tbl.time_s(i);
        if isempty(flightPts), flightPts=fp;
        else,                  flightPts(end+1)=fp; %#ok<AGROW>
        end
    end
end
if isempty(flightPts)
    error('No supersonic points found in flight_data.csv.');
end

[~, i_crit] = max([flightPts.q_inf]);
fp_crit = flightPts(i_crit);
fprintf('  %d supersonic points   Mach %.2f–%.2f\n', ...
        numel(flightPts), min([flightPts.Mach]), max([flightPts.Mach]));
fprintf('  Critical point: Mach=%.3f  q=%.0f Pa  h=%.0f m  t=%.1f s\n\n', ...
        fp_crit.Mach, fp_crit.q_inf, fp_crit.h_m, fp_crit.time);

%% -----------------------------------------------------------------------
%% Step 3.  Build mesh + boundary conditions  (same for all betas)
%% -----------------------------------------------------------------------
fprintf('STEP 3 — Building mesh...\n');
cr = 0.300; ct = 0.150; span = 0.160; sweep_deg = 57.4;
nx = 24;    ny = 12;
sweep_rad = deg2rad(sweep_deg);

mesh     = fem.GenerarMallaAleta(cr, ct, span, sweep_rad, nx, ny);
nNodes   = size(mesh.nodes, 1);
nDOF_tot = 6 * nNodes;
fprintf('  %d nodes   %d Q4 elements  (%d x %d)\n\n', ...
        nNodes, size(mesh.connect, 1), nx, ny);

tol       = 1e-9;
rootNodes = find(mesh.nodes(:,2) < tol);
fixedDOFs = reshape((rootNodes-1)*6 + (1:6), 1, []);
geometry.t = t;

%% -----------------------------------------------------------------------
%% Step 4.  Mass matrix ONCE (mass depends only on geometry and density,
%%          not on the laminate D-matrix)
%% -----------------------------------------------------------------------
fprintf('STEP 4 — Assembling mass matrix (once)...\n');
M_glob = fem.assembleGlobalMass(mesh, rho_m, t);

% Extract free DOFs and reduced mass matrix using a dummy zero stiffness
K_dummy           = sparse(nDOF_tot, nDOF_tot);
[~, M_red, freeDOFs] = fem.applyDirichletBCs(K_dummy, M_glob, fixedDOFs);
fprintf('  Free DOFs: %d  (of %d total)\n\n', numel(freeDOFs), nDOF_tot);

nModes = 6;
k_vals = [0, 0.01, 0.05, 0.1, 0.2, 0.5, 1.0];

%% -----------------------------------------------------------------------
%% Step 5.  Beta loop
%% -----------------------------------------------------------------------
fprintf('STEP 5 — Flutter sweep over %d beta values\n', nCfg);
fprintf('         Critical flight point: Mach=%.3f  q_crit=%.0f Pa\n', ...
        fp_crit.Mach, fp_crit.q_inf);
fprintf('         flutter margin = q_flutter / q_crit  (> 1 means STABLE)\n\n');

% Print table header
fprintf('  %-5s  %-8s  %-8s  %-8s  %-9s  %-13s  %-13s\n', ...
        'beta', 'f1[Hz]', 'f2[Hz]', 'f3[Hz]', 'k_weiss', 'fl_q/q_crit', 'div_q/q_crit');
fprintf('  %s\n', repmat('-', 1, 72));

% Pre-allocate storage
beta_vec      = zeros(nCfg, 1);
k_weiss_vec   = zeros(nCfg, 1);
fl_margin_vec = zeros(nCfg, 1);
div_margin_vec = zeros(nCfg, 1);
freq_mat      = zeros(nCfg, nModes);

for ic = 1:nCfg
    cfg = configs(ic);

    % (a) D_flex for this beta
    D26_val = 0;
    if isfield(cfg, 'D26_Nm'), D26_val = cfg.D26_Nm; end

    D_flex = [cfg.D11_Nm, cfg.D12_Nm, cfg.D16_Nm;
              cfg.D12_Nm, cfg.D22_Nm, D26_val;
              cfg.D16_Nm, D26_val,    cfg.D66_Nm];

    % E_eff derived from D66 of THIS beta (same formula as mainFlutterSolver)
    E_eff      = 12 * cfg.D66_Nm / t^3;
    material.E  = E_eff;
    material.nu = nu_eff;

    % (b) Stiffness matrix
    K_glob = fem.assembleGlobalStiffness(mesh, geometry, material, D_flex);
    [K_red, ~, ~] = fem.applyDirichletBCs(K_glob, M_glob, fixedDOFs);

    % (c) Modal analysis
    [Phi_red, omega_n] = fem.modalAnalysis(K_red, M_red, nModes);
    f_n = omega_n / (2*pi);

    Phi_full = zeros(nDOF_tot, nModes);
    Phi_full(freeDOFs, :) = Phi_red;

    % (d) Generalised aerodynamic forces at critical point
    Q_k      = aero.pistonTheoryGAF(mesh, Phi_full, fp_crit.Mach, ...
                                     fp_crit.q_inf, fp_crit.a, k_vals, sweep_deg);
    Q_k_norm = Q_k / fp_crit.q_inf;   % normalise by reference q

    % (e) Flutter + divergence solve (critical point only)
    [~, ~, flRes] = stability.solveFlutterPL(omega_n, Q_k_norm, k_vals, fp_crit);

    % (f) Extract margins
    fl_m  = flRes.q_flutter_crit / fp_crit.q_inf;
    if isinf(flRes.q_div_crit)
        div_m    = Inf;
        div_str  = '    Inf (free)';
    else
        div_m    = flRes.q_div_crit / fp_crit.q_inf;
        div_str  = sprintf('%13.2f', div_m);
    end

    if isinf(fl_m)
        fl_str = '    Inf (free)';
    else
        fl_str = sprintf('%13.2f', fl_m);
    end

    fprintf('  %-5.0f  %-8.2f  %-8.2f  %-8.2f  %-9.5f  %s  %s\n', ...
            cfg.beta_deg, f_n(1), f_n(2), f_n(3), cfg.k_weiss, fl_str, div_str);

    % Store
    beta_vec(ic)       = cfg.beta_deg;
    k_weiss_vec(ic)    = cfg.k_weiss;
    fl_margin_vec(ic)  = fl_m;
    div_margin_vec(ic) = div_m;
    freq_mat(ic,:)     = f_n;
end

fprintf('  %s\n\n', repmat('-', 1, 72));

% Find best beta (maximum flutter margin)
[best_fl, i_best] = max(fl_margin_vec);
fprintf('RESULT: Best flutter margin = %.2f x q_crit at beta = %.0f deg\n', ...
        best_fl, beta_vec(i_best));
fprintf('        k_weiss at best beta = %.5f\n\n', k_weiss_vec(i_best));

%% -----------------------------------------------------------------------
%% Step 6.  Save results and plots
%% -----------------------------------------------------------------------
save(fullfile(BASE, 'results', 'beta_sweep.mat'), ...
     'beta_vec', 'k_weiss_vec', 'fl_margin_vec', 'div_margin_vec', 'freq_mat');

fig = figure('Color','w', 'Position',[100 100 1000 700]);

% Panel 1 — k_weiss vs beta
ax1 = subplot(2,2,1);
plot(beta_vec, k_weiss_vec, 'b-o', 'LineWidth',1.5, 'MarkerFaceColor','b');
xlabel('beta [deg]'); ylabel('k_{weiss} = D_{16}/\surd(D_{11}D_{66})');
title('Weisshaar coupling parameter');
grid on; xlim([0 45]);
xline(beta_vec(i_best), '--r', sprintf('beta=%.0f', beta_vec(i_best)));

% Panel 2 — flutter margin vs beta
ax2 = subplot(2,2,2);
fl_plot = min(fl_margin_vec, 50);   % cap Inf at 50 for visibility
plot(beta_vec, fl_plot, 'r-s', 'LineWidth',1.5, 'MarkerFaceColor','r');
hold on;
yline(1.0, 'k--', 'Flutter boundary');
xlabel('beta [deg]'); ylabel('q_{flutter} / q_{crit}  [-]');
title('Flutter margin at critical flight point');
grid on; xlim([0 45]);
xline(beta_vec(i_best), '--r', sprintf('best: beta=%.0f', beta_vec(i_best)));

% Panel 3 — natural frequencies vs beta (first 3 modes)
ax3 = subplot(2,2,3);
plot(beta_vec, freq_mat(:,1), 'b-o', 'DisplayName','Mode 1', 'LineWidth',1.5);
hold on;
plot(beta_vec, freq_mat(:,2), 'r-s', 'DisplayName','Mode 2', 'LineWidth',1.5);
plot(beta_vec, freq_mat(:,3), 'g-^', 'DisplayName','Mode 3', 'LineWidth',1.5);
xlabel('beta [deg]'); ylabel('Natural frequency [Hz]');
title('Mode frequencies vs beta');
legend('Location','best'); grid on; xlim([0 45]);

% Panel 4 — D16 and D66 vs beta
ax4 = subplot(2,2,4);
D16_arr = arrayfun(@(c) c.D16_Nm, configs);
D66_arr = arrayfun(@(c) c.D66_Nm, configs);
yyaxis left
plot(beta_vec, D16_arr, 'b-o', 'LineWidth',1.5);
ylabel('D_{16} [N\cdotm]');
yyaxis right
plot(beta_vec, D66_arr, 'r-s', 'LineWidth',1.5);
ylabel('D_{66} [N\cdotm]');
xlabel('beta [deg]'); title('D_{16} and D_{66} vs beta');
grid on; xlim([0 45]);
legend('D_{16}','D_{66}','Location','east');

sgtitle(sprintf('Beta Sweep — %s layup, t=%.0f mm, Mach=%.2f', ...
        info.layup, info.thickness_mm, fp_crit.Mach), 'FontSize',13);

saveas(fig, fullfile(BASE, 'results', 'beta_sweep.png'));
fprintf('Plots saved -> results/beta_sweep.png\n');
fprintf('Data saved  -> results/beta_sweep.mat\n');
